# Put it at your home dir

# Visual Studio Code Caches
rm -rf .config/Code/User/workspaceStorage
rm -rf .cache/vscode-cpptools/ipch

# yay caches
rm -rf .cache/yay/*
rm -rf .local/share/flatpak/*
rm -rf .cache/yarn
rm -rf .cache/electron
rm -rf .cache/pip

# cache generated by wine QQ
rm -rf '文档/Tencent Files'
