[package]
name = "gtk-rs-media"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.3.1", package = "gtk4", features = ["v4_4"]}