#include<time.h>
extern int xeapi1(struct tm *local);
//This header defines a function to calculate the month from 2019.6 to now
//The beginning is 2019.6,and the api version generated by this function >=20
